apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fitness-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: fitness-tracker-app
  updatePolicy:
    updateMode: "Auto"